#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor '^1' -d I II III IV V
bspc monitor '^2' -d VI VII VIII

bspc config focused_border_color '#00aaaa'
bspc config border_width 1
bspc config window_gap 4
bspc config -m '^1' left_padding 46

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

~/.config/bspwm/autostart.sh &
