#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor '^1' -d I II III IV V

bspc config border_width 1
bspc config window_gap 4

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focus_follows_pointer false
bspc config pointer_follows_focus true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

/home/$USER/.config/bspwm/autostart.sh &
